remote_theme: pages-themes/hacker@v0.2.0 # /primer@v0.6.0
title: Advanced Numerical Methods (ANM) in Python
#description: [A short description of your site's purpose]
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
plugins:
- jekyll-remote-theme